language: r

sudo: true
cache: 
  - packages
  - /tmp/texlive
  - /$HOME/.texlive
warnings_are_errors: false

r_packages:
 - assertthat
 - bitops
 - chron
 - colorspace
 - cowplot
 - crayon
 - curl
 - data.table
 - DBI
 - devtools
 - digest
 - dplyr
 - dtplyr
 - evaluate
 - forecast
 - formatR
 - fracdiff
 - ggplot2
 - git2r
 - glmnet
 - grattan
 - gridExtra
 - gtable
 - httr
 - knitr
 - labeling
 - lattice
 - lazyeval
 - lubridate
 - magrittr
 - memoise
 - munsell
 - mfx
 - nloptr
 - nnet
 - plyr
 - quadprog
 - R6
 - Rcpp
 - RCurl
 - readr
 - readxl
 - reshape2
 - rsconnect
 - rsdmx
 - rstudioapi
 - scales
 - showtext
 - showtextdb
 - stringi
 - stringr
 - sysfonts
 - taxstats
 - testthat
 - tibble
 - tidyr
 - timeDate
 - tseries
 - withr
 - XML
 - xtable
 - zoo

r_github_packages:
  - hughparsonage/taxstats
  - hughparsonage/grattan
  - yixuan/showtext


before_install:
  - source ./source/texlive.sh
  - tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
  - tlmgr update --all
  - sudo apt-get update
  - sudo apt-get install texlive-bibtex-extra
  - sudo apt-get install libnlopt-dev  # for nloptr
  - Rscript -e "if (!requireNamespace('littler')) install.packages('littler')"
  - Rscript -e "install.packages('nloptr')"
  - Rscript -e "if (!requireNamespace('knitr')) install.packages('knitr')"

install: echo Installation step #do not remove this line!

before_script:
    # as somehow no biber package is available for ubuntu 12.04 via apt, let's just download it directly
    # - wget "http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/0.9.9/binaries/Linux/biber-linux_x86_64.tar.gz"
    - wget "https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Linux/biber-linux_x86_64.tar.gz"
    - tar xzf biber-linux_x86_64.tar.gz
    - export PATH=$PATH:$PWD
    - tlmgr update biber

script: 
  - set -e
  - Rscript -e "knitr::knit('HP-Cost-overruns-report.Rnw')"
  - pdflatex -draftmode HP-Cost-overruns-report.tex
  - biber HP-Cost-overruns-report
  - Rscript CheckBiber.R
  - pdflatex -draftmode HP-Cost-overruns-report.tex

notifications:
  email: 
    recipients: 
      - hugh.parsonage+CostOverruns@gmail.com
      - lucille.danks16@gmail.com
